-- Add missing columns to products table
ALTER TABLE IF EXISTS products
ADD COLUMN IF NOT EXISTS brand VARCHAR(100),
ADD COLUMN IF NOT EXISTS processor VARCHAR(100),
ADD COLUMN IF NOT EXISTS processor_generation VARCHAR(50),
ADD COLUMN IF NOT EXISTS ram_gb VARCHAR(50),
ADD COLUMN IF NOT EXISTS storage_gb VARCHAR(50),
ADD COLUMN IF NOT EXISTS screen_size VARCHAR(20),
ADD COLUMN IF NOT EXISTS graphics VARCHAR(100),
ADD COLUMN IF NOT EXISTS price_category VARCHAR(50),
ADD COLUMN IF NOT EXISTS is_in_stock BOOLEAN DEFAULT true;
